title: Jazzy Jumpers
hero_image: images/banner.png
description: Create a memory game involving jazzy jumpers
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-1, programming-1, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "scratch"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Parts of the jumper
  - title: New jumper
  - title: Hide the jumper
  - title: "What was on the jumper?"
